### ISSUE TITLE
Wedding - End of night

### ISSUE THREAD

**Issue by brianamarie** [brianamarie/Wedding#1]
# Going in
### Florist
- Flowers
- Centerpieces

### Team 2
- Programs
- Guest book
- Pens for guest book
- Escort cards
- Table numbers

### Hyvee/ Team 3
- Cake
- Forks for bride & groom

### Guests bring
- Gifts/cards

# Going out
### Team 1
- Flowers
- Centerpieces

### Team 2
- Guest book
- Pens for guest book
- Gifts/cards
- Forks for bride & groom (we have a specific set as a gift from @brookeeanet)

### Team 3
- Cake pieces to save

### Leave/trash
- Programs
- Escort cards
- Table numbers

**Comment by brianamarie** [comment]
@brookeeanet What do you think about this?

**Comment by brookeeanet** [comment]
@brianamarie  Is your mom on this?  Because I can totally jump on this.

**Comment by brianamarie** [comment]
@brookeeanet Actually, no she isn't, and I totally forgot about this. If you could help with this, that would be ✨ ❤️ ✨ ❗

**Comment by brookeeanet** [comment]
I can def help.  Let's have an actual summit when you're here next week.  I think it would be good to maybe create a flexible "itinerary" for the timing of everything so we know who will be available to help with stuff like this?

**Comment by brianamarie** [comment]
> I think it would be good to maybe create a flexible "itinerary" for the timing of everything

❤️ @brookeeanet

**Comment by C-Williams** [comment]
So I just noted that the florist is going to set up the centerpieces, and that Hyvee will deliver the cake, however that is all that I've updated.

**Comment by brookeeanet** [comment]
@brianamarie @C-Williams I noticed that you have some guys on gift transportation at the end of the night, but Steve/Bennett/me/my fam are happy to help keep track of some of the other little stuff like cake forks, guest book, and I can bring some tupperware for cake pieces in as well
