### ISSUE TITLE
HoneyFund Account

### ISSUE THREAD

**Issue by C-Williams** [brianamarie/Wedding#12]
- [x] Give Chris Login Info
- [x] Complete Honeyfund Account Setup

@brianamarie

**Comment by brianamarie** [comment]
@C-Williams 👋 ❤️ 😍 

Email - shared
The largest pet name + two numbers...

Let me know if this is too much like code...

**Comment by C-Williams** [comment]
@brianamarie 

Did you finish this up?

**Comment by brianamarie** [comment]
@C-Williams Yes, I did. 😄  They will be giving us $242 on Monday. 🎉 💸 
![screen shot 2016-07-06 at 9 31 01 am](https://cloud.githubusercontent.com/assets/9906718/16621588/6524175a-435c-11e6-836c-af77b69b25d6.png)
