### ISSUE TITLE
Ceremony Outline

### ISSUE THREAD

**Issue by C-Williams** [brianamarie/Wedding#14]
https://docs.google.com/document/d/1o-gCtEQwjaSh4SYnlm4VTI7NxeBSqcwK69FtCOfYl7Q/edit

- [x] Has John looked at this?
- [x] Call John and discuss
- [x] Update doc with changes
- [x] Finalize ceremony by July 16

**Comment by C-Williams** [comment]
@brianamarie 

John has looked at it, but I can't seem to locate any comments he may have made, or maybe he didn't make any. I remember you emailing me that he looked at it, but again I can't find that email.

Also, Github makes these things so much easier to organize.

**Comment by brianamarie** [comment]
@C-Williams I went through and made some small edits. I think the vows could still be fixed a bit.

We need to decide if we want a unity candle thing, and if we want "I Can't Help Falling in Love With You" during it. If so we need to get music to Andrew. ❤️ 🎹

**Comment by C-Williams** [comment]
@brianamarie 

I thought we had decided that we were doing that. I emailed him the music a while ago, just forwarded it to you now.

**Comment by C-Williams** [comment]
@brianamarie 

I ran through this, and it was a bit on the short end, probably somewhere around 15-17 min with processional and unity candle included. So I added back in the vows and some more speaking for John to do.

If you have a brief moment, could you text him and let him know to look at it and double check my additions are ok? I would, but I would feel awkward, so if you could that would be lovely. 

Also, you should look at it too I suppose!

**Comment by brianamarie** [comment]
I messaged him asking him to look it over, and I will look at it tonight! Time for lunch for me 😄 🍔 
Thank you so so so much for doing this!!!!
