### ISSUE TITLE
Saturday, July 9

### ISSUE THREAD

**Issue by C-Williams** [brianamarie/Wedding#16]
What to do today:

- [x] Hunt down RSVPs
- [x] [Fill out schedule with songs for DJ](https://github.com/brianamarie/Wedding/issues/7) 
- [x] Guess numbers for dinner and breakfast
- [x] Buy candles, candle holders, candle stand
- [x] Finalize ceremony

**Comment by brianamarie** [comment]
@C-Williams 👋 


I made a few assumptions: 
Marty & Kelly 👍 
Brett 👍 Paisley & Katie 👎 

Currently we are only waiting on RSVPS from:
- [ ] Debbie & Jim Tabor
- [ ] Rodney & Margie Watt Family
- [ ] Sale Family (from Allegro, probably a no) 

I told Mig we would get back to her with a final count today. Currently it is 130 adults and 12 children.
