### ISSUE TITLE
Day of

### ISSUE THREAD

**Issue by C-Williams** [brianamarie/Wedding#19]
- [x] DJ????
- [x] Drink water
- [x] Book Laki whale watching

**Comment by C-Williams** [comment]
@brianamarie

**Comment by brianamarie** [comment]
@c-williams I haven't heard from the dj but i have my computer. I have to
get started really early and I don't want to call him that early. Can you
or one of your groomsmen call later this morning?

**Comment by C-Williams** [comment]
@brianamarie no problem

**Comment by sodervoce** [comment]
Ok, I literally have absolutely no idea what this GitHub thing is, but I've been browsing through your various threads, and I can't decide if I think it's amazing or scary. Your whole honeymoon itinerary is on here!!! 

Oh, and HI, congratulations, and I'll see you both in a few short hours!!!
