### ISSUE TITLE
Wedding Planning Tracking Issue

### ISSUE THREAD

**Issue by brianamarie** [brianamarie/Wedding#5]
# July 23

#### Bridal Party and Family
| Name  | Role   | Contact       |
|----------------|--------------------------|---------------------|
| 👰 Briana | Bride  | 913-907-4787 |
| 👨 Chris | Groom | 417-224-0044 | 
| Ivy | Mother of the Bride | 913-907-4787 |
| Jim | Father of the Bride | 913-226-3853  |
| Vicki | Mother of the Groom |  417-224-0530 |
| Brooke | Maid of Honor | 913-515-0774 | 
| Ross | Best Man | 417-818-2982 | 
| John | Officiant | 913-488-9388 |
| Allison | Bridesmaid | 913-375-0120 | 
| Samantha | Bridesmaid |               |
| Ana | Bridesmaid |             |
| Rusty | Groomsman | 417-234-2107 |
| Anthony | Groomsman/reader | 417-501-4447 |
| Nate | Reader | 913-548-5431 |

#### Vendors
| Name  | Role   | Contact       |
|----------------|--------------------------|---------------------|
| Mark Allen | [Day of coordinator](https://github.com/brianamarie/Wedding/issues/17) |   |
| Andrew Ouellette | [Pianist](https://github.com/brianamarie/Wedding/issues/4)  |       |
| Kasey Benedict |  [Florist](https://github.com/brianamarie/Wedding/issues/6) | 913-814-0184 | 
| HyVee on Ridgeview| [Cakes](https://github.com/brianamarie/Wedding/issues/3) | 913-393-4150 |
| Christopher Butler, Hi Society Entertainment |  [DJ](https://github.com/brianamarie/Wedding/issues/7) | 702-545-5685 |
| Abby Houseman | [Hair](https://github.com/brianamarie/Wedding/issues/10) | 402-239-5813  |
| Michele Taylor | [Makeup](https://github.com/brianamarie/Wedding/issues/9) |  |
| Bob Stout | [Piano Tuner](https://github.com/brianamarie/Wedding/issues/11) | 816-833-1556 |
| Rebecca Knechtel, CatchLight Photography | [Photographer](https://github.com/brianamarie/Wedding/issues/8) | 913-299-7972 |

### Day-of schedule:

| Time  | What                     | Where       | Who                                           |
|-------|--------------------------|-------------|-----------------------------------------------|
| 8:30 | Makeup & Hair starting time TBA    |  AC Marriott   | Bridal party, Abby, Michele |
| 10:00 |                          |             |                                               |
| 11:00 | Flowers and setup        | Californos | Florist                                       |
| 11:00 | Jimmy Johns delivery | AC Marriott | Rusty |
| 12:00 |                          |             |                                               |
| 12:30 | Pick up flower thingys   | Californos     | Pauly and Jane                      |
| 12:45 |  Photographer 1 start details, dress, 1st look with Jim   | AC Marriott  | Photographer 1, Briana, Bridesmaids, Ivy, Jim   |
| 1:00  |                          |             |                                               |
| 1:30  | Photographer 2 with Chris & Groomsmen      | AC Marriott |  Photographer 2, Chris, Groomsmen, Vicki    |
| 2:15  | 1st look, couples photos | Californos | Chris, Briana, Photographers                  |
| 3:00  | Couples photos           | Around town | Chris, Briana, Photographers                  |
| 4:00 | Piano tuning | Californos | Bob Stout |
| 4:15  | Bridal party photos      | Westport    | Bridal party, photographers                   |
| 5:00  | Photographer set up for family formals  | Californos | Photographers |
| 5:15  | Formal photos            | Californos | Bridal party, immediate family, photographers |
| 6:00  |                          |             |                                               |
| 6:15  |  Piano music starts                    | Californos deck            |  Andrew, Mark give check to Andrew                                             |
| 6:30  | Ceremony                 | Californos |                                               |
| 7:00  | Start reception          | Californos | DJ, guests  |
| 7:30  | Entrance, then dinner        | Californos  |                                               |
| 8:00  | Toasts, first dances     | Californos |                                               |
| 9:00  |                          |  Californos |                                               |
| 10:00 | Take out gifts           | Californos  | Nate, Ben, Frankie, and Ross      |
| 11:00 | End dancing              |  Californos | DJ                                            |

# ⚠️  Other Help Needed ⚠️ 
- [x] Getting arrangements out next morning

**Comment by C-Williams** [comment]
@brianamarie 

checked off a few, just double check, make sure florist is completely done.

**Comment by C-Williams** [comment]
@brianamarie 

Added in Tony's and Nate's numbers and read through the schedule, it looks pretty good to me.

Have you heard anything from the photographer about the times for her? It looks like you might have, but I'm not finding it our email. Just want to make sure that her plans and ours mesh. If you haven't heard anything, I will email her Monday.

Also, did you send this updated version out recently? I am not seeing that listed in the sent mail.

Hope your flight went well! Sorry to add any undue stress!

<3

**Comment by C-Williams** [comment]
@brianamarie 

Where is that guest table list? Debbie and Jim can't come anymore, so we need to take them off.

**Comment by brianamarie** [comment]
> Have you heard anything from the photographer about the times for her? It looks like you might have, but I'm not finding it our email. Just want to make sure that her plans and ours mesh. If you haven't heard anything, I will email her Monday.

@C-Williams Thank you! I think an extra email would be ✨ just to be sure. 



> Also, did you send this updated version out recently?

No, since there were only minimal changes to the contact part and no big changes to the schedule, I did not. You can if you'd like but don't feel like you have to. 


> Where is that guest table list? Debbie and Jim can't come anymore, so we need to take them off.

It is in the wedding address document under "Confirmed RSVP" tab.

❤️ ❤️

**Comment by brianamarie** [comment]
@C-Williams @brookeeanet New challenge - Carseat from Chris's mom to airport for @crichID and her son. Maybe with help of @beardofedu & @hollenberry. @crichID's flight gets in at 1:08 PM on Saturday 🎉 ✈️

**Comment by crichID** [comment]
@brianamarie I actually just called the car rental company and I was able to add a car seat to the reservation! Yay! :tada: Thank you so much for looking out for Austin - he can't wait to meet everyone!
