### ISSUE TITLE
DJ

### ISSUE THREAD

**Issue by brianamarie** [brianamarie/Wedding#7]
Contact info still needed

**Tuesday, July 12**

- [x] Touch base with Chris (DJ) to confirm times
<img width="592" alt="screen shot 2016-07-09 at 10 04 34 am" src="https://cloud.githubusercontent.com/assets/9906718/16708530/94b3a9ec-45bc-11e6-99f2-e7a9bb9962d1.png">

- [x] Give him list of requests 
<img width="879" alt="screen shot 2016-07-09 at 10 26 30 am" src="https://cloud.githubusercontent.com/assets/9906718/16708606/a28b687c-45bf-11e6-8ff1-19f9f631983d.png">

**Day of**

- [x] Pay remainder of balance ($350)

**Comment by C-Williams** [comment]
@brianamarie 

Updated with schedule. After we finalize RSVP's we can look at requests and think of maybe a few songs, 10?, for requests, something you can't live without. Include those in email finalizing schedule.

**Comment by brianamarie** [comment]
## Special Songs
- First Couple Dance: The Gambler, Fun. (only a smaller cut of it, not the whole thing) 
- Father & Daughter Dance: 
- Mother & Son Dance: My Wish, Rascall Flatts 


## Other Requests
- You Make My Dreams Come True, Hall & Oates (Nate & Kaia Swift)
- Colors of the Wind, Pocohantas (Brooke & Steve Eanet) 
- Kei$ha! (Kate Koegel) 
- Billie Jean, Michael Jackson (Hannah Fakhouri) 
- At Last, Etta James (Harry & Jo Hofer)
- Will You Still Love Me When I'm 64?, The Beatles (Linda Annaberg & Michael Farley)
- Can I have this Dance, Anne Murray (Ginny Swift)
- PYT, Michael Jackson (Lindsay Eanet)
- Kiss By a Rose, Seal (Carlos Viveros) 
- Afternoon Delight, Anchorman (Megan Charlé)
- Work, Rihanna (Matt Desmond)

**Comment by brianamarie** [comment]
![screen shot 2016-07-13 at 5 06 41 pm](https://cloud.githubusercontent.com/assets/9906718/16821494/322e21c2-491c-11e6-8254-e41067fce7f7.png)
