### ISSUE TITLE
Photographer

### ISSUE THREAD

**Issue by brianamarie** [brianamarie/Wedding#8]
Contact info needed

- [x] Double check that we don't have to do anything else until the wedding 😄

**Comment by C-Williams** [comment]
@brianamarie 

There's an email strain between you and Rebecca on the wedding email that talks about a call that happened...did that happen? If not, we could set up another call to go over exact details of that day with her. I could make the call next week, just need to know if I need to.

**Comment by brianamarie** [comment]
We did have that conversation while I was in SF a monthish ago.  The current schedule reflects our conversation. 😄 📆
